### ISSUE TITLE
[Feature] Allow resources to be embedded using the include_bytes! macro

### ISSUE THREAD

**Issue by DusterTheFirst** [UberLambda/ttspico-rs#4]
It would be useful to not have to depend upon the Text Analysis and Speech Generation binary files when running and would be beneficial if they could be stored in the program binary, and loaded into the pico system through passing their contents, rather than a file path.

**Comment by UberLambda** [comment]
Hello! I currently do not have much time to work on this project, so this could take a while. A merge request would be welcome, however!

There would be some issues with the implementation:

1) This feature would make the compiled binary much larger.
    (This is not really a problem unless you have low RAM - like on a Raspi).
2) This makes it harder to pick only the TA, SGs that you need (unless you just embed them all...)  
    One could add a Cargo feature flag to select exactly which languages to embed, and which to keep in files.
3) The Pico C library itself seems to want filepaths to resources, not `FILE*`s or similar.  
    The C code would need to be patched to support byte buffers directly.

**Comment by DusterTheFirst** [comment]
After I left the issue, i dug into the implementation and came across the same issues. It would be a novel idea, but as you stated, it would be impractical for the little benefit that one would gain. Thanks for your response and your work on this project so far!

**Comment by UberLambda** [comment]
@DusterTheFirst I could see why this could be useful (PhysFS comes to mind) but yeah, it could be a non-negligible amount of work.  
I guess it's better closed for now - but I will come back to it if I have the time :)
